name: Go-Linux
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:

  build-and-test-linux:
    name: Build Linux and test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get dependencies
      run: go get -v -t -d ./...
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Test
      run: ./scripts/check-coverage.sh 80
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SYSL_PLANTUML: http://www.plantuml.com/plantuml

    - name: Build
      run: go build -v ./...
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install
      run: |
        export GOBIN=$PWD/bin
        mkdir $GOBIN
        GIT_TAG="$(echo $GITHUB_REF | cut -d'/' -f3)"
        ./scripts/build.sh install ${GIT_TAG:1} ${GITHUB_SHA} ${OSTYPE}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Test installed
      run: ./scripts/test-gosysl.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOPATH: .
        SYSL_PLANTUML: http://www.plantuml.com/plantuml

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash) -f ./coverage.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
