name: python-darwin
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:

  build-and-test-python:
    name: Build and test python sysl on darwin
    runs-on: macOS-latest
    steps:

    - name: Set up python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: '2.7'
        architecture: 'x64'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check out code
      uses: actions/checkout@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get dependencies
      run: |
        pip install flake8==3.5.0
        pip install . pytest
        pip install codecov -e .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Test installed
      run: ./scripts/test-pysysl.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SYSL_PLANTUML: http://www.plantuml.com/plantuml
